### ISSUE TITLE
scmpc v0.2.2 not working anymore

### ISSUE THREAD

**Issue by dddesign** [cmende/scmpc#10]
I use scmpc 0.2.2 with my openwrt kamikaze router, but it's not working anymore. I know there are newer version of scmpc but for my openwrt version kamikaze I need 0.2.2! I think the problem is the the audioscrobbler protocol 1.1 isn't supported anymore. I checked with [protocol 1.2](http://www.audioscrobbler.net/development/protocol/), this is working with small changes in the code. but because I'm not familiar with coding C I kindly ask you if you can change to code of scmpc 0.2.2 so it would work with protocol 1.2!
thanks a lot
j

**Comment by nyxdis** [comment]
May I ask what's wrong with newer scmpc versions instead?

**Comment by dddesign** [comment]
my os (openwrt kamikaze) don't support the necessary dependencies (eg. libmpdclient). but any way I can't compile your package for kamikaze, so I mad my own bash script. thanks anyway
